package lv.javaguru.training.lesson15.homework;

import java.util.LinkedList;
import java.util.List;

public class Cities {

    public static List<City> get() {
        List<City> cities = new LinkedList<>();
        cities.add(new City("Ādaži", 7482));
        cities.add(new City("Ainaži", 701));
        cities.add(new City("Aizkraukle", 7198));
        cities.add(new City("Aizpute", 4128));
        cities.add(new City("Aknīste", 995));
        cities.add(new City("Aloja", 1073));
        cities.add(new City("Alūksne", 6945));
        cities.add(new City("Ape", 832));
        cities.add(new City("Auce", 2360));
        cities.add(new City("Baldone", 3789));
        cities.add(new City("Baloži", 6992));
        cities.add(new City("Balvi", 6103));
        cities.add(new City("Bauska", 10202));
        cities.add(new City("Brocēni", 3009));
        cities.add(new City("Cēsis", 16190));
        cities.add(new City("Cesvaine", 1280));
        cities.add(new City("Dagda", 1887));
        cities.add(new City("Daugavpils", 86872));
        cities.add(new City("Dobele", 9031));
        cities.add(new City("Durbe", 520));
        cities.add(new City("Grobiņa", 3778));
        cities.add(new City("Gulbene", 7171));
        cities.add(new City("Iecava", 5677));
        cities.add(new City("Ikšķile", 7698));
        cities.add(new City("Ilūkste", 2312));
        cities.add(new City("Jaunjelgava", 1825));
        cities.add(new City("Jēkabpils", 22134));
        cities.add(new City("Jelgava", 58154));
        cities.add(new City("Jūrmala", 56862));
        cities.add(new City("Kandava", 3501));
        cities.add(new City("Kārsava", 1970));
        cities.add(new City("Koknese", 2562));
        cities.add(new City("Krāslava", 7771));
        cities.add(new City("Kuldīga", 10395));
        cities.add(new City("Ķegums", 2147));
        cities.add(new City("Ķekava", 5190));
        cities.add(new City("Lielvārde", 6085));
        cities.add(new City("Liepāja", 73333));
        cities.add(new City("Līgatne", 1092));
        cities.add(new City("Limbaži", 7059));
        cities.add(new City("Līvāni", 7388));
        cities.add(new City("Lubāna", 1555));
        cities.add(new City("Ludza", 7767));
        cities.add(new City("Madona", 7129));
        cities.add(new City("Mazsalaca", 1143));
        cities.add(new City("Mārupe", 1796));
        cities.add(new City("Ogre", 24075));
        cities.add(new City("Olaine", 10475));
        cities.add(new City("Pāvilosta", 850));
        cities.add(new City("Piltene", 877));
        cities.add(new City("Pļaviņas", 2950));
        cities.add(new City("Preiļi", 6326));
        cities.add(new City("Priekule", 1912));
        cities.add(new City("Rēzekne", 28785));
        cities.add(new City("Rīga", 655090));
        cities.add(new City("Rūjiena", 2766));
        cities.add(new City("Sabile", 1430));
        cities.add(new City("Salacgrīva", 2624));
        cities.add(new City("Salaspils", 18602));
        cities.add(new City("Saldus", 10168));
        cities.add(new City("Saulkrasti	", 3430));
        cities.add(new City("Seda", 1197));
        cities.add(new City("Sigulda", 14817));
        cities.add(new City("Skrunda", 1985));
        cities.add(new City("Smiltene", 5334));
        cities.add(new City("Staicele", 861));
        cities.add(new City("Stende", 1605));
        cities.add(new City("Strenči", 1042));
        cities.add(new City("Subate", 591));
        cities.add(new City("Talsi", 9350));
        cities.add(new City("Tukums", 17572));
        cities.add(new City("Valdemārpils", 1234));
        cities.add(new City("Valka", 4935));
        cities.add(new City("Valmiera", 24269));
        cities.add(new City("Vangaži", 3512));
        cities.add(new City("Varakļāni", 1755));
        cities.add(new City("Ventspils", 35660));
        cities.add(new City("Viesīte", 1530));
        cities.add(new City("Viļaka", 1245));
        cities.add(new City("Viļāni", 2831));
        cities.add(new City("Zilupe", 1369));
        return cities;
    }

}
